language: python
sudo: false
cache:
  directories:
  - container
python:
- '2.7'
- '3.4'
install:
 - eval "$(curl -LSs --connect-timeout 2 --retry 100 public-travis-scripts.polysquare.org/bootstrap.py | python /dev/stdin -d $(pwd)/container -s container-setup.py -e bash -p /dev/stdout)"
script:
 - polysquare_run check/python/check.py
before_cache:
 - polysquare_cleanup
after_success:
 - polysquare_run coverage/python/coverage.py
